name: mypy
description: Type checks Python code.
runs:
  using: composite
  steps:
    - name: mypy dcspy
      shell: powershell
      run: |
        ./venv/scripts/activate
        mypy dcspy

    - name: mypy tests
      shell: powershell
      run: |
        ./venv/scripts/activate
        mypy tests
