name: Build dcspy binary packages
description: Assembles the full dcspy application.
runs:
  using: composite
  steps:
    - name: "Compile and install PyInstaller"
      shell: bash
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        pyi_tag=$(python latest_tag.py pyinstaller 1)
        pyi_ver=$(python latest_tag.py pyinstaller 0)
        cd pyinstaller/bootloader
        git checkout $pyi_tag
        python.exe ./waf all
        cd ..
        python -m build
        python -m twine check dist/*
        pip install dist/pyinstaller-$pyi_ver-py3-none-any.whl

    - name: "Generate version info file"
      shell: bash
      run: |
        python generate_ver_file.py

    - name: "Build dcspy package"
      shell: bash
      run: |
        python -m build
        python -m twine check dist/*

    - name: "Build dcspy binaries"
      shell: bash
      run: |
        export SOURCE_DATE_EPOCH=1674687685
        export PYTHONHASHSEED=1674687685
        pyinstaller --clean --noconfirm --log-level DEBUG dcspy.spec
        pyinstaller --clean --noconfirm --log-level DEBUG dcspy_cli.spec
        pyinstaller --clean --noconfirm --log-level DEBUG dcspy_onedir.spec
        md5sum dist/*.exe
        unset PYTHONHASHSEED
        unset SOURCE_DATE_EPOCH
        pyi-bindepend dist/*.exe

    - name: "Set Nuitka data"
      shell: pwsh
      id: nuitka_data
      run: |
        $sha = $Env:GITHUB_SHA
        Write-Output "git_sha=$sha" >> $env:GITHUB_OUTPUT
        $ref_name = $Env:GITHUB_REF_NAME
        Write-Output "git_ref_name=$ref_name" >> $env:GITHUB_OUTPUT
        $run_number = $Env:GITHUB_RUN_NUMBER
        Write-Output "git_run_number=$run_number" >> $env:GITHUB_OUTPUT

    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: 2.4.8
        script-name: dcs_py.py
        onefile: true
        windows-console-mode: disable
        prefer-source-code: true
        enable-plugins: pyside6
        include-package-data: src/dcspy
        assume-yes-for-downloads: true
        onefile-windows-splash-screen-image: src/dcspy/img/splash.png
        output-file: dcspy_nuitka
        output-dir: dist
        windows-icon-from-ico: src/dcspy/img/dcspy_white.ico
        product-name: DCSpy
        file-version: ${{ steps.nuitka_data.outputs.git_ref_name }}.${{ steps.nuitka_data.outputs.git_sha }}
        product-version: ${{ steps.nuitka_data.outputs.git_ref_name }}.${{ steps.nuitka_data.outputs.git_run_number }}
        file-description: Integrating DCS Planes with Logitech keyboards with LCD
        copyright: (c) 2024 Michal Plichta. All rights reserved.

    - name: "Compress to zip"
      shell: bash
      run: |
        cd dist
        ls -la
        /c/Program\ Files/7-Zip/7z.exe a -bt dcspy.zip dcs_py
        7z.exe a -bt dcspy.zip dcs_py
