name: Build dcspy binary packages
description: Assembles the full dcspy application.
runs:
  using: composite
  steps:
    - name: Choco help
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install -y visualstudio2022-workload-vctools

    - name: Compile and install PyInstaller
      shell: powershell
      run: |
        ./venv/scripts/activate
        Write-Output "Clone PyInstaller"
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller
        git checkout v5.10.1
        cd bootloader
        Write-Output "Bulid WAF"
        python.exe ./waf all
        cd ..
        Write-Output "Build package wheel"
        python.exe setup.py bdist_wheel
        Write-Output "Install PyInstaller"
        pip install  dist\pyinstaller-*.whl

    - name: Make version file
      shell: powershell
      run: |
        ./venv/scripts/activate
        python gnerate_ver_file.py $env:GITHUB_REF_NAME $env:GITHUB_RUN_NUMBER $env:GITHUB_SHA file_version_info.txt

    - name: Build dcspy binaries
      shell: powershell
      run: |
        ./venv/scripts/activate
        pyinstaller --clean --noconfirm --log-level INFO dcspy.spec
        pyinstaller --clean --noconfirm --log-level INFO dcspy_cli.spec

    - name: Install changelog
      shell: powershell
      run: |
        Copy-Item .\CHANGELOG.md .\dist
