name: Build dcspy binary packages
description: Assembles the full dcspy application.
runs:
  using: composite
  steps:
#    - name: Install VisualStudio 2022
#      uses: crazy-max/ghaction-chocolatey@v2
#      with:
#        args: install -y visualstudio2022-workload-vctools

    - name: Compile and install PyInstaller
      shell: bash
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        pyi_tag=$(python.exe latest_tag.py pyinstaller 1)
        pyi_ver=$(python.exe latest_tag.py pyinstaller 0)
        cd pyinstaller/bootloader
        git checkout $pyi_tag
        python.exe ./waf all
        cd ..
        python.exe setup.py bdist_wheel
        pip install dist/pyinstaller-$pyi_ver-py3-none-any.whl

    - name: Generate version info file
      shell: bash
      run: |
        python generate_ver_file.py $GITHUB_REF_NAME $GITHUB_RUN_NUMBER $GITHUB_SHA file_version_info.txt

    - name: Build dcspy package
      shell: bash
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
        python -m twine check dist/*

    - name: Build dcspy binaries
      shell: bash
      run: |
        pyinstaller --clean --noconfirm --log-level INFO dcspy.spec
        pyinstaller --clean --noconfirm --log-level INFO dcspy_cli.spec
