name: Build dcspy binary packages
description: Assembles the full dcspy application.
runs:
  using: composite
  steps:
    - name: Install VisualStudio 2022
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install -y visualstudio2022-workload-vctools

    - name: Compile and install PyInstaller
      shell: powershell
      run: |
        ./venv/scripts/activate
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller
        git checkout v5.10.1
        cd bootloader
        python.exe ./waf all
        cd ..
        python.exe setup.py bdist_wheel
        pip install dist\pyinstaller-5.10.1-py3-none-any.whl

    - name: Generate version info file
      shell: powershell
      run: |
        ./venv/scripts/activate
        python generate_ver_file.py $env:GITHUB_REF_NAME $env:GITHUB_RUN_NUMBER $env:GITHUB_SHA file_version_info.txt

    - name: Build dcspy binaries
      shell: powershell
      run: |
        ./venv/scripts/activate
        pyinstaller --clean --noconfirm --log-level INFO dcspy.spec
        pyinstaller --clean --noconfirm --log-level INFO dcspy_cli.spec

    - name: Build dcspy package
      shell: powershell
      run: |
        ./venv/scripts/activate
        pip install -U twine
        python setup.py sdist bdist_wheel

    - name: Install changelog
      shell: powershell
      run: |
        Copy-Item .\CHANGELOG.md .\dist
