name: Build dcspy binary packages
description: Assembles the full dcspy application.
runs:
  using: composite
  steps:
#    - name: Install VisualStudio 2022
#      uses: crazy-max/ghaction-chocolatey@v2
#      with:
#        args: install -y visualstudio2022-workload-vctools

    - name: Compile and install PyInstaller
      shell: powershell
      run: |
        ./venv/scripts/activate
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller
        Get-ChildItem 
        pwd
        cd ..
        Get-ChildItem
        pwd
        cd pyi
        Get-ChildItem
        $pyi_tag = python.exe ..\pyi\latest_tag.py . 1
        $pyi_ver = python.exe ..\pyi\latest_tag.py . 0
        $pyi_tag
        $pyi_ver
        git checkout $pyi_tag
        cd bootloader
        python.exe ./waf all
        cd ..
        python.exe setup.py bdist_wheel
        pip install dist\pyinstaller-$pyi_ver-py3-none-any.whl

    - name: Generate version info file
      shell: powershell
      run: |
        ./venv/scripts/activate
        python generate_ver_file.py $env:GITHUB_REF_NAME $env:GITHUB_RUN_NUMBER $env:GITHUB_SHA file_version_info.txt

    - name: Build dcspy binaries
      shell: powershell
      run: |
        ./venv/scripts/activate
        pyinstaller --clean --noconfirm --log-level INFO dcspy.spec
        pyinstaller --clean --noconfirm --log-level INFO dcspy_cli.spec
        Get-ChildItem -Recurse -Depth 1

    - name: Build dcspy package
      shell: powershell
      run: |
        ./venv/scripts/activate
        pip install -U twine
        python setup.py sdist bdist_wheel
        Get-ChildItem -Recurse -Depth 1
        python -m twine check dist/*

    - name: Install changelog
      shell: powershell
      run: |
        Copy-Item .\CHANGELOG.md .\dist
