name: Build dcspy binary packages
description: Assembles the full dcspy application.
runs:
  using: composite
  steps:
    - name: "Compile and install PyInstaller"
      shell: bash
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        pyi_tag=$(python latest_tag.py pyinstaller 1)
        pyi_ver=$(python latest_tag.py pyinstaller 0)
        cd pyinstaller/bootloader
        git checkout $pyi_tag
        python.exe ./waf all
        cd ..
        python -m build
        python -m twine check dist/*
        pip install dist/pyinstaller-$pyi_ver-py3-none-any.whl

    - name: "Generate version info file"
      shell: bash
      run: |
        python generate_ver_file.py

    - name: "Build dcspy package"
      shell: bash
      run: |
        python -m build
        python -m twine check dist/*

    - name: "Build dcspy binaries PyInstaller"
      shell: bash
      run: |
        export SOURCE_DATE_EPOCH=1674687685
        export PYTHONHASHSEED=1674687685
        pyinstaller --clean --noconfirm --log-level DEBUG dcspy.spec
        pyinstaller --clean --noconfirm --log-level DEBUG dcspy_cli.spec
        pyinstaller --clean --noconfirm --log-level DEBUG dcspy_onedir.spec
        md5sum dist/*.exe
        unset PYTHONHASHSEED
        unset SOURCE_DATE_EPOCH
        pyi-bindepend dist/*.exe

    - name: "Build dcspy binaries with Nuitka"
      shell: bash
      run: |
        python -m nuitka --onefile --disable-console --report=compilation-report.xml --plugin-enable=pyside6 --include-package-data=dcspy --assume-yes-for-downloads --onefile-windows-splash-screen-image=dcspy/img/splash.png --output-filename=dcspy_nuitka --output-dir=dist --windows-icon-from-ico=dcspy/img/dcspy_white.ico --product-name=DCSpy --file-version=3.0.0.0 --product-version=3.0.0.0 --file-description="Integrating DCS Planes with Logitech keyboards with LCD" --copyright="(c) 2024 Michal Plichta. All rights reserved." dcs_py.py

    - name: "Compress to zip"
      shell: bash
      run: |
        cd dist
        ls -la
        /c/Program\ Files/7-Zip/7z.exe a -bt dcspy.zip dcs_py
        7z.exe a -bt dcspy.zip dcs_py
