name: Python environment set-up
description: Sets up the dcspy Python environment.
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip

#    - name: Install virtual environment
#      shell: bash
#      run: |
#        python -m venv ./venv

    - name: Install requirements
      shell: bash
      run: |
#        ./venv/scripts/activate
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements_test.txt
