name: Coverage

on:
  workflow_call:

jobs:
  coverage:
    name: windows-latest py3.12
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Test with pytest"
        run: |
          python -m pytest -q --disable-warnings --cov=dcspy --cov-report=xml --cov-report=html --cov-report=term-missing -m "not dcsbios"

      - name: "Upload pytest results"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage_3_12
          path: |
            covhtml/*
            coverage.xml
          retention-days: 4
