name: Coverage

on:
  workflow_call:

jobs:
  coverage:
    name: ubuntu-latest py3.12
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Install MS Fonts"
        run: |
          curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
          sudo mkdir -p /usr/share/fonts/truetype
          sudo mv consola.ttf /usr/share/fonts/truetype
          fc-cache -f

      - name: "Test with pytest"
        run: |
          python -m pytest -q --disable-warnings --cov=dcspy --cov-report=xml --cov-report=html --cov-report=term-missing -m "not dcsbios"

      - name: "Upload pytest results"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage_3_12
          path: |
            covhtml/*
            coverage.xml
          retention-days: 4
