name: Build

on: workflow_call

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Install cibuildwheel"
        run: pip install cibuildwheel

      - name: "VS setup env"
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: "Build wheels"
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
