name: Build_all

on: workflow_call

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "VS setup env"
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: "Compile lupa"
        shell: cmd
        run: |
          git clone https://github.com/scoder/lupa.git
          cd lupa
          pip install -U setuptools==67.2.0 wheel cython cibuildwheel
          git submodule init
          git submodule update
          copy /y ..\scripts\setup setup.py
          dir

      - name: "Build wheels"
        shell: cmd
        run: |
          dir
          cd lupa
          python -m cibuildwheel --output-dir wheelhouse

      - name: "dir"
        shell: cmd
        run: |
          cd lupa
          dir wheelhouse

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
