name: Build_all

on: workflow_call

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Compile lupa"
        shell: cmd
        run: |
          git clone https://github.com/scoder/lupa.git
          cd lupa
          git submodule init
          git submodule update
          copy /y ..\scripts\setup setup.py
          dir

      - name: "Build wheels"
        shell: cmd
        run: |
          dir ..
          call C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          copy /y ..\scripts\setup setup.py
          type setup.py
          pip install -U pip setuptools wheel cython cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
#        env:
#          CIBW_SKIP: cp36-win*

      - name: "dir"
        shell: cmd
        run: |
          cd lupa
          dir wheelhouse

      - name: "Upload"
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
