name: Build dcspy binary with Nuitka

on: workflow_call

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        nuitka_type: [ dcspy_nuitka, dcspy_nuitka_cli ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Python environment"
        uses: ./.github/actions/setup-python

      - name: "Generate version info file"
        shell: pwsh
        id: nuitka_data
        run: |
          python -m pip install -U pyinstaller
          $output = & python scripts/generate_ver_file.py
          $output = $output -replace "[\(\)\s\']", ""
          $values = $output.Split(',')
          $ref_name = $values[0].Trim()
          $run_number = $values[1].Trim()
          $sha = $values[2].Trim()
          Write-Output "git_ref_name=$ref_name" >> $env:GITHUB_OUTPUT
          Write-Output "git_run_number=$run_number" >> $env:GITHUB_OUTPUT
          Write-Output "git_sha=$sha" >> $env:GITHUB_OUTPUT

      - name: "Build dcspy binaries with Nuitka"
        if: ${{ endsWith( matrix.nuitka_type, '_nuitka') }}
        shell: bash
        run: |
          python -m nuitka --onefile --windows-console-mode=disable --prefer-source-code --plugin-enable=pyside6 --include-package-data=dcspy --assume-yes-for-downloads --onefile-windows-splash-screen-image=src/dcspy/img/splash.png --output-filename=${{ matrix.nuitka_type }}2 --output-dir=dist --windows-icon-from-ico=src/dcspy/img/dcspy_white.ico --product-name=DCSpy --file-version=${{ steps.nuitka_data.outputs.git_ref_name }}.${{ steps.nuitka_data.outputs.git_run_number }} --product-version=${{ steps.nuitka_data.outputs.git_ref_name }}.${{ steps.nuitka_data.outputs.git_sha }} --file-description="Integrating DCS Planes with Logitech keyboards with LCD" --copyright="(c) 2024 Michal Plichta. All rights reserved." src/dcs_py.py

      - name: "Build dcspy binaries with Nuitka"
        if: ${{ endsWith( matrix.nuitka_type, '_cli') }}
        shell: bash
        run: |
          python -m nuitka --onefile --windows-console-mode=force --prefer-source-code --plugin-enable=pyside6 --include-package-data=dcspy --assume-yes-for-downloads --onefile-windows-splash-screen-image=src/dcspy/img/splash.png --output-filename=${{ matrix.nuitka_type }}2 --output-dir=dist --windows-icon-from-ico=src/dcspy/img/dcspy_white.ico --product-name=DCSpy --file-version=${{ steps.nuitka_data.outputs.git_ref_name }}.${{ steps.nuitka_data.outputs.git_run_number }} --product-version=${{ steps.nuitka_data.outputs.git_ref_name }}.${{ steps.nuitka_data.outputs.git_sha }} --file-description="Integrating DCS Planes with Logitech keyboards with LCD" --copyright="(c) 2024 Michal Plichta. All rights reserved." src/dcs_py.py

      - name: "Upload dcspy binaries"
        uses: actions/upload-artifact@v4
        with:
          name: nuitka_${{ matrix.nuitka_type }}2
          path: dist/${{ matrix.nuitka_type }}2.exe
