name: Python CI

on:
  push:
    branches: [ "*" ]
    tags-ignore: [ "v*" ]

jobs:
  style:
    uses: ./.github/workflows/style.yml

  test:
    needs: [ style ]
    uses: ./.github/workflows/test.yml

  license:
    needs: [ style ]
    uses: ./.github/workflows/license.yml

  coverage:
    needs: [ style ]
    uses: ./.github/workflows/coverage.yml
