name: Release Pipeline

on:
  push:
    tags: ["v*"]

jobs:
  style:
    uses: ./.github/workflows/style.yml

  test:
    needs: [style]
    uses: ./.github/workflows/test.yml

  build:
    needs: [test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: ./.github/actions/setup-python

      - name: Build dcspy
        uses: ./.github/actions/build-app

      - uses: actions/upload-artifact@v3
        with:
          name: dcspy_binaries
          path: dist/

  release:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: ./.github/actions/setup-python

      - uses: actions/download-artifact@v3
        with:
          name: dcspy_binaries

      - name: "Get Release Notes"
        id: version
        run: |
          ./venv/scripts/activate
          $dcspy_ver = python.exe latest_tag.py . 0
          Rename-Item -Path dcs_py.exe -NewName dcspy_$dcspy_ver.exe
          Rename-Item -Path dcs_py_cli.exe -NewName dcspy_cli_$dcspy_ver.exe
          Write-Host $dcspy_ver
          Write-Output "::set-output name=number::$dcspy_ver"
          $changelog = Get-Content .\CHANGELOG.md
          $last_change = ($changelog | Select-String -Pattern "^##\s" | Select-Object -Skip 1 -First 1).LineNumber - 2
          ($changelog | Select-Object -First $last_change) -join "`n" | Out-File .\RELEASENOTES.md

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.PYI_REL_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: dcspy ${{ github.ref }}
          body_path: RELEASENOTES.md
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PYI_REL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dcspy_${{ steps.version.outputs.number }}.exe
          asset_name: dcspy_${{ steps.version.outputs.number }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PYI_REL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dcspy_cli_${{ steps.version.outputs.number }}.exe
          asset_name: dcspy_cli_${{ steps.version.outputs.number }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PYI_REL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dcspy-${{ steps.version.outputs.number }}-py3-none-any.whl
          asset_name: dcspy-${{ steps.version.outputs.number }}-py3-none-any.whl
          asset_content_type: application/x-wheel+zip

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PYI_REL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dcspy-${{ steps.version.outputs.number }}.tar.gz
          asset_name: dcspy-${{ steps.version.outputs.number }}.tar.gz
          asset_content_type: application/tar+gzip/

  pypi:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools twine

      - uses: actions/download-artifact@v3
        with:
          name: dcspy_binaries

      - name: Publish dcspy to PyPI
        run: |
          mkdir dist
          mv *.whl *.tar.gz dist/
          ls -la dist/

#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_TOKEN }}
#          skip_existing: true
#          verbose: true
