name: Python lint

on: workflow_call

jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -Ur requirements_test.txt

      - name: Check PyCodeStyle
        run: |
          ./venv/scripts/activate
          pycodestyle --statistics --count dcspy

      - name: Check PyDocStyle
        run: |
          pydocstyle --count dcspy

      - name: Check interrogate
        run: |
          interrogate -c pyproject.toml -vv

      - name: Check PyLint
        run: |
          pylint dcspy || echo $(($? % 4))

      - name: Check flake8
        run: |
          flake8 . --select=E9,F63,F7,F82 --show-source
          flake8 . --exit-zero --ignore=E501

      - name: Check mypy
        run: |
          mypy dcspy

      - name: Upload mypy results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mypy_3_11
          path: |
            mypyhtml/*
          retention-days: 4

      - name: Check MANIFEST
        run: |
          check-manifest -q || echo $(($? -1))        
