name: Tests

on: workflow_call

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: ./.github/actions/setup-python-${{ matrix.os }}

      - name: Install MS Fonts
        if: ${{ contains( matrix.os, 'ubuntu') }}
        run: |
          curl -O https://lexics.github.io/assets/downloads/fonts/clearTypeFonts/consola.ttf
          sudo mkdir -p /usr/share/fonts/truetype
          sudo mv consola.ttf /usr/share/fonts/truetype
          fc-cache -f -v

      - name: Test with pytest
        run: |
          ./venv/scripts/activate
          python -m pytest --random -q --disable-warnings -m "not dcsbios"

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: pytest-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            dcspy.log
          retention-days: 5

      - name: Check pip-audit
        run: |
          ./venv/scripts/activate
          pip-audit -r requirements.txt --progress-spinner off
