name: Tests
on: workflow_call
jobs:
  python-tests:
    name: Python tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: ./.github/actions/setup-python

      - name: run tests
        shell: powershell
        run: |
          ./venv/scripts/activate
          python -m pytest --random -q --disable-warnings -m "not dcsbios"
